{% set name = "elyra-python-editor-extension" %}
{% set version = "2.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elyra-python-editor-extension-{{ version }}.tar.gz
  sha256: 055a8ca0a04ada517f91c6d1233432c9d0c51d4c88daa7667eb003df981fb9d8

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - elyra-server ==2.2.2
    - python >=3.6

test:
  commands:
    - exit 0

about:
  home: https://github.com/elyra-ai/elyra
  summary: Elyra JupyterLab extension providing support for Python scripts. Learn more at https://elyra.readthedocs.io/en/stable/user_guide/enhanced-script-support.html
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akchinSTC
    - lresende
